### ISSUE TITLE
 java.lang.RuntimeException: java.lang.RuntimeException: class net.ripe.hadoop.pcap.DnsPcapReader not net.ripe.hadoop.pcap.PcapReader

### ISSUE THREAD

**Issue by mfaisal** [RIPE-NCC/hadoop-pcap#24]
Hi,

I am using cdh5.4.0 and following steps. But got following run time error. Please help.

hive> add jar hadoop-pcap-serde-1.1-SNAPSHOT-jar-with-dependencies.jar;
Added [hadoop-pcap-serde-1.1-SNAPSHOT-jar-with-dependencies.jar] to class path
Added resources: [hadoop-pcap-serde-1.1-SNAPSHOT-jar-with-dependencies.jar]
hive> SET hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat; 
hive> SET mapred.max.split.size=104857600;
hive> SET net.ripe.hadoop.pcap.io.reader.class=net.ripe.hadoop.pcap.DnsPcapReader;
hive> CREATE EXTERNAL TABLE pcaps (ts bigint,
    >                              ts_usec decimal,
    >                              protocol string,
    >                              src string,
    >                              src_port int,
    >                              dst string,
    >                              dst_port int,
    >                              len int,
    >                              ttl int,
    >                              dns_queryid int,
    >                              dns_flags string,
    >                              dns_opcode string,
    >                              dns_rcode string,
    >                              dns_question string,
    >                              dns_answer array<string>,
    >                              dns_authority array<string>,
    >                              dns_additional array<string>)
    > ROW FORMAT SERDE 'net.ripe.hadoop.pcap.serde.PcapDeserializer'
    > STORED AS INPUTFORMAT 'net.ripe.hadoop.pcap.io.PcapInputFormat'
    >           OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
    > LOCATION 'hdfs://localhost:8020/pcaps/';
OK
Time taken: 0.355 seconds
hive> select * from pcaps limit 2;

OK
java.lang.RuntimeException: java.lang.RuntimeException: class net.ripe.hadoop.pcap.DnsPcapReader not net.ripe.hadoop.pcap.PcapReader
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2144)
	at net.ripe.hadoop.pcap.io.PcapInputFormat.initPcapReader(PcapInputFormat.java:56)
	at net.ripe.hadoop.pcap.io.PcapInputFormat.initPcapRecordReader(PcapInputFormat.java:50)
	at net.ripe.hadoop.pcap.io.PcapInputFormat.getRecordReader(PcapInputFormat.java:38)
	at org.apache.hadoop.hive.ql.exec.FetchOperator$FetchInputFormatSplit.getRecordReader(FetchOperator.java:667)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:323)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:445)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:414)
	at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:138)
	at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1655)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:227)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:159)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:370)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:756)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:675)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:615)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.RuntimeException: class net.ripe.hadoop.pcap.DnsPcapReader not net.ripe.hadoop.pcap.PcapReader
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2138)
	... 21 more
Failed with exception java.io.IOException:java.lang.NullPointerException
Time taken: 0.162 seconds

Best Regards,
Mustafa

**Comment by wnagele** [comment]
Can you please try the JARs from the official release and see if the problem persists: http://dl.bintray.com/hadoop-pcap/hadoop-pcap/

Looks like a compilation problem in your snapshot.

**Comment by mfaisal** [comment]
It is not a compilation problem as I run this with apache hadoop 2.6 with hive 1.1.0 and works fine.
Any way I remove CDH5.4 from my system at this moment for this reason can not test right now.
However, I tried with these JARs before and they were working nice with Apache hadoop and hive.

Thanks for your response.

**Comment by quanter007** [comment]
I had the same problem when the client environment in Hive worked fine and I had the same error when SQL was submitted to the pyhive environment.
